"use client";

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export default function PaymentSettingsPage() {
  const [settings, setSettings] = useState({ accountName: '', bankName: '', accountNumber: '', ifsc: '', upiId: '', qrUrl: '', mobileNumber: '', pendingPaymentAccess: true });
  const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/admin/payment-settings').then((response) => response.json()).then((result) => { const value = result.settings ?? {}; setSettings({ accountName: value.payment_account_name ?? '', bankName: value.payment_bank_name ?? '', accountNumber: value.payment_account_number ?? '', ifsc: value.payment_ifsc ?? '', upiId: value.payment_upi_id ?? '', qrUrl: value.payment_qr_url ?? '', mobileNumber: value.payment_mobile_number ?? '', pendingPaymentAccess: value.pending_payment_access !== false }); }); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/payment-settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); setMessage(response.ok ? 'Payment account settings saved.' : 'Unable to save settings.'); }
  return <div className="max-w-xl space-y-6"><div><h1 className="text-2xl font-bold text-foreground">Payment account</h1><p className="mt-1 text-sm text-muted-foreground">Configure the manual payment instructions customers see on Billing.</p></div><form onSubmit={save} className="space-y-4 rounded-xl border border-border bg-card p-5"><Input placeholder="UPI ID" value={settings.upiId} onChange={(e) => setSettings({ ...settings, upiId: e.target.value })} /><Input placeholder="UPI QR code URL (optional)" value={settings.qrUrl} onChange={(e) => setSettings({ ...settings, qrUrl: e.target.value })} /><Input placeholder="Company payment/mobile number" value={settings.mobileNumber} onChange={(e) => setSettings({ ...settings, mobileNumber: e.target.value })} /><Input placeholder="Bank name" value={settings.bankName} onChange={(e) => setSettings({ ...settings, bankName: e.target.value })} /><Input placeholder="Account name" value={settings.accountName} onChange={(e) => setSettings({ ...settings, accountName: e.target.value })} /><Input placeholder="Account number" value={settings.accountNumber} onChange={(e) => setSettings({ ...settings, accountNumber: e.target.value })} /><Input placeholder="IFSC" value={settings.ifsc} onChange={(e) => setSettings({ ...settings, ifsc: e.target.value })} /><label className="flex items-center gap-2 text-sm text-foreground"><input type="checkbox" checked={settings.pendingPaymentAccess} onChange={(e) => setSettings({ ...settings, pendingPaymentAccess: e.target.checked })} /> Keep customer access active while payment verification is pending</label><Button type="submit">Save payment settings</Button>{message && <p className="text-sm text-muted-foreground">{message}</p>}</form></div>;
}